package pl.edu.atar.universityrecruitment.rules.knowledgeable

import pl.edu.atar.universityrecruitment.Candidate;

// Kwalifikacja olimpijska
rule "Olympic qualification (three_sets_of_rules_salience_lock-on-active_bonus_MODIFY)"
    dialect "java"
    salience 300
    lock-on-active true
    when
        $uc : Candidate(olympicFinalist == true)
    then
        modify($uc) {
            setExamResult(2 * $uc.getExamResult())
        }
        $uc.appendLogger("Agenda '" + drools.getKieRuntime().getAgenda().toString() + "' got focus!");
        $uc.appendLogger("Rule '" + drools.getRule().getName() + "' from package '" + drools.getRule().getPackageName() + "' fired!");
end