package pl.edu.atar.universityrecruitment.rules.knowledgeable

import pl.edu.atar.universityrecruitment.Candidate;

// Informatyka
rule "Exam Qualification / Informatyka (three_sets_of_rules_salience_lock-on-active_bonus_MODIFY)"
    dialect "java"
    salience 100
    when
        $uc : Candidate(examResult > 100, fieldOfStudy == "Informatyka")
    then
        $uc.setAdmission(true);
        $uc.setQualificationType("Exam qualification");
        $uc.appendLogger("Agenda '" + drools.getKieRuntime().getAgenda().toString() + "' got focus!");
        $uc.appendLogger("Rule '" + drools.getRule().getName() + "' from package '" + drools.getRule().getPackageName() + "' fired!");
end

// Automatyka i robotyka
rule "Exam Qualification / Automatyka i robotyka (three_sets_of_rules_salience_lock-on-active_bonus_MODIFY)"
    dialect "java"
    salience 100
    when
        $uc : Candidate(examResult > 60, fieldOfStudy == "Automatyka i robotyka")
    then
        $uc.setAdmission(true);
        $uc.setQualificationType("Exam qualification");
        $uc.appendLogger("Agenda '" + drools.getKieRuntime().getAgenda().toString() + "' got focus!");
        $uc.appendLogger("Rule '" + drools.getRule().getName() + "' from package '" + drools.getRule().getPackageName() + "' fired!");
end

// Elektrotechnika
rule "Exam Qualification / Elektrotechnika (three_sets_of_rules_salience_lock-on-active_bonus_MODIFY)"
    dialect "java"
    salience 100
    when
        $uc : Candidate(examResult > 80, fieldOfStudy == "Elektrotechnika")
    then
        $uc.setAdmission(true);
        $uc.setQualificationType("Exam qualification");
        $uc.appendLogger("Agenda '" + drools.getKieRuntime().getAgenda().toString() + "' got focus!");
        $uc.appendLogger("Rule '" + drools.getRule().getName() + "' from package '" + drools.getRule().getPackageName() + "' fired!");
end