package pl.edu.atar.universityrecruitment.rules.masterful

import pl.edu.atar.universityrecruitment.Candidate;

// Kwalifikacja olimpijska
rule "Olympic qualification (two_sets_of_rules_salience_activation-group_MODIFY_PropertyReactive)"
    dialect "java"
    salience 200
    activation-group "group-1"
    when
        $uc : Candidate(olympicFinalist == true) @Watch(!*)
    then
        modify($uc) {
            setAdmission(true),
            setQualificationType("Olympic qualification.")
        }
        $uc.appendLogger("Agenda '" + drools.getKieRuntime().getAgenda().toString() + "' got focus!");
        $uc.appendLogger("Rule '" + drools.getRule().getName() + "' from package '" + drools.getRule().getPackageName() + "' fired!");
end