package pl.edu.atar.universityrecruitment.rules.masterful

import pl.edu.atar.universityrecruitment.Candidate;

// Informatyka
rule "Exam Qualification / Informatyka (two_sets_of_rules_salience_activation-group_MODIFY_PropertyReactive)"
    dialect "java"
    salience 100
    activation-group "group-1"
    when
        $uc : Candidate(examResult > 100, fieldOfStudy == "Informatyka") @Watch(!*)
    then
        modify($uc) {
            setAdmission(true),
            setQualificationType("Exam qualification")
        }
        $uc.appendLogger("Agenda '" + drools.getKieRuntime().getAgenda().toString() + "' got focus!");
        $uc.appendLogger("Rule '" + drools.getRule().getName() + "' from package '" + drools.getRule().getPackageName() + "' fired!");
end

// Automatyka i robotyka
rule "Exam Qualification / Automatyka i robotyka (two_sets_of_rules_salience_activation-group_MODIFY_PropertyReactive)"
    dialect "java"
    salience 100
    activation-group "group-1"
    when
        $uc : Candidate(examResult > 60, fieldOfStudy == "Automatyka i robotyka") @Watch(!*)
    then
        modify($uc) {
            setAdmission(true),
            setQualificationType("Exam qualification")
        }
        $uc.appendLogger("Agenda '" + drools.getKieRuntime().getAgenda().toString() + "' got focus!");
        $uc.appendLogger("Rule '" + drools.getRule().getName() + "' from package '" + drools.getRule().getPackageName() + "' fired!");
end

// Elektrotechnika
rule "Exam Qualification / Elektrotechnika (two_sets_of_rules_salience_activation-group_MODIFY_PropertyReactive)"
    dialect "java"
    salience 100
    activation-group "group-1"
    when
        $uc : Candidate(examResult > 80, fieldOfStudy == "Elektrotechnika") @Watch(!*)
    then
        modify($uc) {
            setAdmission(true),
            setQualificationType("Exam qualification")
        }
        $uc.appendLogger("Agenda '" + drools.getKieRuntime().getAgenda().toString() + "' got focus!");
        $uc.appendLogger("Rule '" + drools.getRule().getName() + "' from package '" + drools.getRule().getPackageName() + "' fired!");
end