package pl.edu.atar.universityrecruitment.rules.elementary.onesetofrulesnoloopmodify

import pl.edu.atar.universityrecruitment.Candidate;

// Informatyka
rule "Exam Qualification / Informatyka (one_set_of_rules_no-loop_MODIFY)"
    dialect "java"
    no-loop true
    when
        $uc : Candidate(examResult > 100, fieldOfStudy == "Informatyka")
    then
        modify($uc) {
            setAdmission(Boolean.TRUE),
            setQualificationType("Exam qualification"),
            incrementCounter()
        }
        $uc.appendLogger("Agenda '" + drools.getKieRuntime().getAgenda().toString() + "' got focus!");
        $uc.appendLogger("Rule '" + drools.getRule().getName() + "' from package '" + drools.getRule().getPackageName() + "' fired!");
end

// Automatyka i robotyka
rule "Exam Qualification / Automatyka i robotyka (one_set_of_rules_no-loop_MODIFY)"
    dialect "java"
    no-loop true
    when
        $uc : Candidate(examResult > 60, fieldOfStudy == "Automatyka i robotyka")
    then
        modify($uc) {
            setAdmission(Boolean.TRUE),
            setQualificationType("Exam qualification"),
            incrementCounter()
        }
        $uc.appendLogger("Agenda '" + drools.getKieRuntime().getAgenda().toString() + "' got focus!");
        $uc.appendLogger("Rule '" + drools.getRule().getName() + "' from package '" + drools.getRule().getPackageName() + "' fired!");
end

// Elektrotechnika
rule "Exam Qualification / Elektrotechnika (one_set_of_rules_no-loop_MODIFY)"
    dialect "java"
    no-loop true
    when
        $uc : Candidate(examResult > 80, fieldOfStudy == "Elektrotechnika")
    then
        modify($uc) {
            setAdmission(Boolean.TRUE),
            setQualificationType("Exam qualification"),
            incrementCounter()
        }
        $uc.appendLogger("Agenda '" + drools.getKieRuntime().getAgenda().toString() + "' got focus!");
        $uc.appendLogger("Rule '" + drools.getRule().getName() + "' from package '" + drools.getRule().getPackageName() + "' fired!");
end