package pl.edu.atar.universityrecruitment.rules.elementary.onesetofrules

import pl.edu.atar.universityrecruitment.Candidate

// Informatyka
rule "Exam Qualification / Informatyka (one_set_of_rules)"
    dialect "java"
    when
        $uc : Candidate(examResult > 100, fieldOfStudy == "Informatyka")
    then
        $uc.setAdmission(Boolean.TRUE);
        $uc.setQualificationType("Exam qualification");
        $uc.appendLogger("Agenda '" + drools.getKieRuntime().getAgenda().toString() + "' got focus!");
        $uc.appendLogger("Rule '" + drools.getRule().getName() + "' from package '" + drools.getRule().getPackageName() + "' fired!");
end

// Automatyka i robotyka
rule "Exam Qualification / Automatyka i robotyka (one_set_of_rules)"
    dialect "java"
    when
        $uc : Candidate(examResult > 60, fieldOfStudy == "Automatyka i robotyka")
    then
        $uc.setAdmission(Boolean.TRUE);
        $uc.setQualificationType("Exam qualification");
        $uc.appendLogger("Agenda '" + drools.getKieRuntime().getAgenda().toString() + "' got focus!");
        $uc.appendLogger("Rule '" + drools.getRule().getName() + "' from package '" + drools.getRule().getPackageName() + "' fired!");
end

// Elektrotechnika
rule "Exam Qualification / Elektrotechnika (one_set_of_rules)"
    dialect "java"
    when
        $uc : Candidate(examResult > 80, fieldOfStudy == "Elektrotechnika")
    then
        $uc.setAdmission(Boolean.TRUE);
        $uc.setQualificationType("Exam qualification");
        $uc.appendLogger("Agenda '" + drools.getKieRuntime().getAgenda().toString() + "' got focus!");
        $uc.appendLogger("Rule '" + drools.getRule().getName() + "' from package '" + drools.getRule().getPackageName() + "' fired!");
end